In [1]:
import sentence_transformers
import pandas as pd
import numpy as np
import os
from camel_tools.utils.dediac import dediac_ar
from camel_tools.utils.normalize import normalize_alef_ar,normalize_teh_marbuta_ar,normalize_alef_maksura_ar
from tqdm import tqdm


/home/shk/Documents/projects/python/ML/Summer/projects/islam/islamvenv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("Omartificial-Intelligence-Space/GATE-AraBert-v1")



Loading weights: 100%|██████████| 199/199 [00:00<00:00, 6580.68it/s]


tensor([[1.0000, 0.7320, 1.0000, 0.4491],
        [0.7320, 1.0000, 0.7320, 0.5130],
        [1.0000, 0.7320, 1.0000, 0.4491],
        [0.4491, 0.5130, 0.4491, 1.0000]])


In [11]:
import re
import string

puncs = string.punctuation
re_puncs = re.compile(rf'[{puncs}0-9]')


In [13]:
sentences = [
    re_puncs.sub('',normalize_alef_ar(dediac_ar("""حَدَّثَنَا مُسَدَّدٌ، حَدَّثَنَا يَحْيَى، عَنِ الْحَجَّاجِ الصَّوَّافِ، حَدَّثَنِي يَحْيَى بْنُ أَبِي كَثِيرٍ، عَنْ هِلاَلِ بْنِ أَبِي مَيْمُونَةَ، عَنْ عَطَاءِ بْنِ يَسَارٍ، عَنْ مُعَاوِيَةَ بْنِ الْحَكَمِ السُّلَمِيِّ، قَالَ قُلْتُ ‏:‏ يَا رَسُولَ اللَّهِ جَارِيَةٌ لِي صَكَكْتُهَا صَكَّةً ‏.‏ فَعَظَّمَ ذَلِكَ عَلَىَّ رَسُولُ اللَّهِ صلى الله عليه وسلم فَقُلْتُ أَفَلاَ أُعْتِقُهَا قَالَ ‏:‏ ‏"‏ ائْتِنِي بِهَا ‏"‏ ‏.‏ قَالَ ‏:‏ فَجِئْتُ بِهَا قَالَ ‏:‏ ‏"‏ أَيْنَ اللَّهُ ‏"‏ ‏.‏ قَالَتْ ‏:‏ فِي السَّمَاءِ ‏.‏ قَالَ ‏:‏ ‏"‏ مَنْ أَنَا ‏"‏ ‏.‏ قَالَتْ ‏:‏ أَنْتَ رَسُولُ اللَّهِ ‏.‏ قَالَ ‏:‏ ‏"‏ أَعْتِقْهَا فَإِنَّهَا مُؤْمِنَةٌ ‏"‏ ‏.‏"""))),
    re_puncs.sub('',normalize_alef_ar(dediac_ar("""حَدَّثَنَا مُسَدَّدٌ، حَدَّثَنَا يَحْيَى، عَنِ الْحَجَّاجِ الصَّوَّافِ، حَدَّثَنِي يَحْيَى بْنُ أَبِي كَثِيرٍ، عَنْ هِلاَلِ بْنِ أَبِي مَيْمُونَةَ، عَنْ عَطَاءِ بْنِ يَسَارٍ، عَنْ مُعَاوِيَةَ بْنِ الْحَكَمِ السُّلَمِيِّ، قَالَ حَدَّثَنَا مُحَمَّدُ بْنُ الْحَسَنِ بْنِ تَسْنِيمٍ الْعَتَكِيُّ، حَدَّثَنَا مُحَمَّدُ بْنُ بَكْرٍ، أَخْبَرَنَا سَوَّارٌ أَبُو حَمْزَةَ، حَدَّثَنَا عَمْرُو بْنُ شُعَيْبٍ، عَنْ أَبِيهِ، عَنْ جَدِّهِ، قَالَ جَاءَ رَجُلٌ مُسْتَصْرِخٌ إِلَى النَّبِيِّ صلى الله عليه وسلم فَقَالَ جَارِيَةٌ لَهُ يَا رَسُولَ اللَّهِ ‏.‏ فَقَالَ ‏"‏ وَيْحَكَ مَا لَكَ ‏"‏ ‏.‏ قَالَ شَرًّا أَبْصَرَ لِسَيِّدِهِ جَارِيَةً لَهُ فَغَارَ فَجَبَّ مَذَاكِيرَهُ ‏.‏ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ عَلَىَّ بِالرَّجُلِ ‏"‏ ‏.‏ فَطُلِبَ فَلَمْ يُقْدَرْ عَلَيْهِ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ اذْهَبْ فَأَنْتَ حُرٌّ ‏"‏ ‏.‏ فَقَالَ يَا رَسُولَ اللَّهِ عَلَى مَنْ نُصْرَتِي قَالَ ‏"‏ عَلَى كُلِّ مُؤْمِنٍ ‏"‏ ‏.‏ أَوْ قَالَ ‏"‏ كُلِّ مُسْلِمٍ ‏"‏ ‏.‏ قَالَ أَبُو دَاوُدَ الَّذِي عُتِقَ كَانَ اسْمُهُ رَوْحُ بْنُ دِينَارٍ ‏.‏ قَالَ أَبُو دَاوُدَ الَّذِي جَبَّهُ زِنْبَاعٌ ‏.‏ قَالَ أَبُو دَاوُدَ هَذَا زِنْبَاعٌ أَبُو رَوْحٍ كَانَ مَوْلَى الْعَبْدِ ‏.‏"""))),
    re_puncs.sub('',normalize_alef_ar(dediac_ar("""حَدَّثَنَا مُسَدَّدٌ، حَدَّثَنَا يَحْيَى، عَنِ الْحَجَّاجِ الصَّوَّافِ، حَدَّثَنِي يَحْيَى بْنُ أَبِي كَثِيرٍ، عَنْ هِلاَلِ بْنِ أَبِي مَيْمُونَةَ، عَنْ عَطَاءِ بْنِ يَسَارٍ، عَنْ مُعَاوِيَةَ بْنِ الْحَكَمِ السُّلَمِيِّ، قَالَ قُلْتُ ‏:‏ يَا رَسُولَ اللَّهِ جَارِيَةٌ لِي صَكَكْتُهَا صَكَّةً ‏.‏ فَعَظَّمَ ذَلِكَ عَلَىَّ رَسُولُ اللَّهِ صلى الله عليه وسلم فَقُلْتُ أَفَلاَ أُعْتِقُهَا قَالَ ‏:‏ ‏"‏ ائْتِنِي بِهَا ‏"‏ ‏.‏ قَالَ ‏:‏ فَجِئْتُ بِهَا قَالَ ‏:‏ ‏"‏ أَيْنَ اللَّهُ ‏"‏ ‏.‏ قَالَتْ ‏:‏ فِي السَّمَاءِ ‏.‏ قَالَ ‏:‏ ‏"‏ مَنْ أَنَا ‏"‏ ‏.‏ قَالَتْ ‏:‏ أَنْتَ رَسُولُ اللَّهِ ‏.‏ قَالَ ‏:‏ ‏"‏ أَعْتِقْهَا فَإِنَّهَا مُؤْمِنَةٌ ‏"‏ ‏.‏ """))),
    "ما هي الادلة التي تثبت ان الله في السماء"
]
embeddings = model.encode(sentences)

similarities = model.similarity(embeddings, embeddings)
print(similarities)

tensor([[1.0000, 0.7212, 1.0000, 0.1719],
        [0.7212, 1.0000, 0.7212, 0.1851],
        [1.0000, 0.7212, 1.0000, 0.1719],
        [0.1719, 0.1851, 0.1719, 1.0000]])


In [14]:
sentences = [
    normalize_alef_ar(dediac_ar("""حَدَّثَنَا مُسَدَّدٌ، حَدَّثَنَا يَحْيَى، عَنِ الْحَجَّاجِ الصَّوَّافِ، حَدَّثَنِي يَحْيَى بْنُ أَبِي كَثِيرٍ، عَنْ هِلاَلِ بْنِ أَبِي مَيْمُونَةَ، عَنْ عَطَاءِ بْنِ يَسَارٍ، عَنْ مُعَاوِيَةَ بْنِ الْحَكَمِ السُّلَمِيِّ، قَالَ قُلْتُ ‏:‏ يَا رَسُولَ اللَّهِ جَارِيَةٌ لِي صَكَكْتُهَا صَكَّةً ‏.‏ فَعَظَّمَ ذَلِكَ عَلَىَّ رَسُولُ اللَّهِ صلى الله عليه وسلم فَقُلْتُ أَفَلاَ أُعْتِقُهَا قَالَ ‏:‏ ‏"‏ ائْتِنِي بِهَا ‏"‏ ‏.‏ قَالَ ‏:‏ فَجِئْتُ بِهَا قَالَ ‏:‏ ‏"‏ أَيْنَ اللَّهُ ‏"‏ ‏.‏ قَالَتْ ‏:‏ فِي السَّمَاءِ ‏.‏ قَالَ ‏:‏ ‏"‏ مَنْ أَنَا ‏"‏ ‏.‏ قَالَتْ ‏:‏ أَنْتَ رَسُولُ اللَّهِ ‏.‏ قَالَ ‏:‏ ‏"‏ أَعْتِقْهَا فَإِنَّهَا مُؤْمِنَةٌ ‏"‏ ‏.‏""")),
    normalize_alef_ar(dediac_ar("""حَدَّثَنَا مُسَدَّدٌ، حَدَّثَنَا يَحْيَى، عَنِ الْحَجَّاجِ الصَّوَّافِ، حَدَّثَنِي يَحْيَى بْنُ أَبِي كَثِيرٍ، عَنْ هِلاَلِ بْنِ أَبِي مَيْمُونَةَ، عَنْ عَطَاءِ بْنِ يَسَارٍ، عَنْ مُعَاوِيَةَ بْنِ الْحَكَمِ السُّلَمِيِّ، قَالَ حَدَّثَنَا مُحَمَّدُ بْنُ الْحَسَنِ بْنِ تَسْنِيمٍ الْعَتَكِيُّ، حَدَّثَنَا مُحَمَّدُ بْنُ بَكْرٍ، أَخْبَرَنَا سَوَّارٌ أَبُو حَمْزَةَ، حَدَّثَنَا عَمْرُو بْنُ شُعَيْبٍ، عَنْ أَبِيهِ، عَنْ جَدِّهِ، قَالَ جَاءَ رَجُلٌ مُسْتَصْرِخٌ إِلَى النَّبِيِّ صلى الله عليه وسلم فَقَالَ جَارِيَةٌ لَهُ يَا رَسُولَ اللَّهِ ‏.‏ فَقَالَ ‏"‏ وَيْحَكَ مَا لَكَ ‏"‏ ‏.‏ قَالَ شَرًّا أَبْصَرَ لِسَيِّدِهِ جَارِيَةً لَهُ فَغَارَ فَجَبَّ مَذَاكِيرَهُ ‏.‏ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ عَلَىَّ بِالرَّجُلِ ‏"‏ ‏.‏ فَطُلِبَ فَلَمْ يُقْدَرْ عَلَيْهِ فَقَالَ رَسُولُ اللَّهِ صلى الله عليه وسلم ‏"‏ اذْهَبْ فَأَنْتَ حُرٌّ ‏"‏ ‏.‏ فَقَالَ يَا رَسُولَ اللَّهِ عَلَى مَنْ نُصْرَتِي قَالَ ‏"‏ عَلَى كُلِّ مُؤْمِنٍ ‏"‏ ‏.‏ أَوْ قَالَ ‏"‏ كُلِّ مُسْلِمٍ ‏"‏ ‏.‏ قَالَ أَبُو دَاوُدَ الَّذِي عُتِقَ كَانَ اسْمُهُ رَوْحُ بْنُ دِينَارٍ ‏.‏ قَالَ أَبُو دَاوُدَ الَّذِي جَبَّهُ زِنْبَاعٌ ‏.‏ قَالَ أَبُو دَاوُدَ هَذَا زِنْبَاعٌ أَبُو رَوْحٍ كَانَ مَوْلَى الْعَبْدِ ‏.‏""")),
    normalize_alef_ar(dediac_ar("""حَدَّثَنَا مُسَدَّدٌ، حَدَّثَنَا يَحْيَى، عَنِ الْحَجَّاجِ الصَّوَّافِ، حَدَّثَنِي يَحْيَى بْنُ أَبِي كَثِيرٍ، عَنْ هِلاَلِ بْنِ أَبِي مَيْمُونَةَ، عَنْ عَطَاءِ بْنِ يَسَارٍ، عَنْ مُعَاوِيَةَ بْنِ الْحَكَمِ السُّلَمِيِّ، قَالَ قُلْتُ ‏:‏ يَا رَسُولَ اللَّهِ جَارِيَةٌ لِي صَكَكْتُهَا صَكَّةً ‏.‏ فَعَظَّمَ ذَلِكَ عَلَىَّ رَسُولُ اللَّهِ صلى الله عليه وسلم فَقُلْتُ أَفَلاَ أُعْتِقُهَا قَالَ ‏:‏ ‏"‏ ائْتِنِي بِهَا ‏"‏ ‏.‏ قَالَ ‏:‏ فَجِئْتُ بِهَا قَالَ ‏:‏ ‏"‏ أَيْنَ اللَّهُ ‏"‏ ‏.‏ قَالَتْ ‏:‏ فِي السَّمَاءِ ‏.‏ قَالَ ‏:‏ ‏"‏ مَنْ أَنَا ‏"‏ ‏.‏ قَالَتْ ‏:‏ أَنْتَ رَسُولُ اللَّهِ ‏.‏ قَالَ ‏:‏ ‏"‏ أَعْتِقْهَا فَإِنَّهَا مُؤْمِنَةٌ ‏"‏ ‏.‏ """)),
    "ما هي الادلة التي تثبت ان الله في السماء"
]
embeddings = model.encode(sentences)

similarities = model.similarity(embeddings, embeddings)
print(similarities)

tensor([[1.0000, 0.7320, 1.0000, 0.1826],
        [0.7320, 1.0000, 0.7320, 0.1936],
        [1.0000, 0.7320, 1.0000, 0.1826],
        [0.1826, 0.1936, 0.1826, 1.0000]])
